### Python slicing and indexing

In [16]:
lst = [1, 2, 3, 5, 9]
print(lst[-1])
print(lst[-2])

9
5


In [8]:
# 1D slicing
lst = list(range(10))
print(lst[2:5])
print(lst[:4]) # start omitted
print(lst[5:]) # stop omitted
print(lst[::2]) # both start and stop omitted, step=2
print(lst[::-1]) # reverse list

[2, 3, 4]
[0, 1, 2, 3]
[5, 6, 7, 8, 9]
[0, 2, 4, 6, 8]
[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


In [10]:
# 2D slicing
import numpy as np
arr = np.arange(20).reshape(4,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [11]:
print(arr[:, -3:]) # last 3 columns of every row

[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [12]:
print(arr[:2, 1:4])

[[1 2 3]
 [6 7 8]]


In [14]:
print(arr[2,3])

13


In [15]:
arr[2,3] = 99 # in numpy array, slicing returns a view, so changing the slice can change the original array
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 99, 14],
       [15, 16, 17, 18, 19]])

In [19]:
arr[::2, 1:3]

array([[ 1,  2],
       [11, 12]])